---
- name: Install chrony.
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Customize main chrony config file.
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    insertafter: EOF
  notify: Restart chrony
  loop:
    - regexp: '^pool\s+'
      line: "pool 2.debian.pool.ntp.org iburst noselect"
    - regexp: '^maxupdateskew.+'
      line: "maxupdateskew 0"
    - regexp: '^makestep.+'
      line: "makestep 0 0"

- name: Customize other chrony configuration.
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/chrony/conf.d/{{ item }}"
    mode: 0644
  notify: Restart chrony
  with_items:
    - allow.conf
    - refclock.conf

- name: Ensure chrony is running.
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
